server.port: 8082
security.basic.enabled: false

spring:
  data:
    mongodb:
      uri: mongodb://localhost/cfDeployer_local
      port: 27017

---
spring.profiles: test

spring:
  data:
    mongo:
      uri: mongodb://localhost/cfDeployer_test
      port: 27017
